SSISTeam9/Models/ChargeBack.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace SSISTeam9.Models
{
    public class ChargeBack
    {
        public long Id { get; set; }
        public int MonthOfOrder { get; set; }
        public int YearOfOrder { get; set; }
        public long DeptId { get; set; }
        public string DeptName { get; set; }
        public double Amount { get; set; }

    }
}

SSISTeam9/Controllers/ChargeBackController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using SSISTeam9.Models;
using SSISTeam9.Services;
using SSISTeam9.Filters;

namespace SSISTeam9.Controllers
{
    public class ChargeBackController : Controller
    {
        [StoreAuthorisationFilter]
        public ActionResult Select(string sessionId)
        {
            List<string> months = new List<string>
            {
                "January", "February", "March", "April", "May", "June", "July","August","September","October","November", "December"
            };
            List<int> years = new List<int>();
            int currentYear = DateTime.Now.Year;
            for(int i= 0; i < 5; i++)
            {
                years.Add(currentYear - i);
            }
            List<string> depts = DepartmentService.GetAllDepartmentNames();

            ViewData["months"] = months;
            ViewData["years"] = years;
            ViewData["depts"] = depts;

            List<ChargeBack> chargeBacks = (List<ChargeBack>)TempData["chargeBacks"];
            ViewData["chargeBacks"] = chargeBacks;
            int? mode = (int?)TempData["mode"];
            ViewData["mode"] = mode;
            ChargeBack chargeback = (ChargeBack)TempData["chargeback"];
            ViewData["chargeback"] = chargeback;
            ViewData["sessionId"] = sessionId;
            return View();
        }

        public ActionResult Generate(int mode, ChargeBack chargeBack, string sessionId)
        {

            if (mode == 1)
            {
                List<ChargeBack> chargeBacks = ChargeBackService.GetChargeBackByMonth(chargeBack.MonthOfOrder);
                TempData["chargeBacks"] = chargeBacks;
                TempData["mode"] = mode;
                TempData["chargeback"] = chargeBack;
                ViewData["sessionId"] = sessionId;
            }
            if(mode == 2)
            {
                chargeBack.DeptId = DepartmentService.GetDeptIdByName(chargeBack.DeptName);
                List<ChargeBack> chargeBacks = ChargeBackService.GetChargeBackByDept(chargeBack.DeptId, chargeBack.YearOfOrder);
                TempData["chargeBacks"] = chargeBacks;
                TempData["mode"] = mode;
                TempData["chargeback"] = chargeBack;
                ViewData["sessionId"] = sessionId;
            }
        
            return RedirectToAction("Select", new { sessionid = sessionId });
        }


        public ActionResult DeptPastRequisition(long deptId, string sessionId)
        {

            ViewData["sessionId"] = sessionId;
            ViewData["deptName"] = DepartmentService.GetDepartmentById(deptId).DeptName;
            List<Requisition> reqList = RequisitionService.GetPastRequisitionByDeptId(deptId);
            reqList.Sort((x, y) => DateTime.Compare(y.DateOfRequest, x.DateOfRequest));
            return View(reqList);
        }

    }
}

SSISTeam9/Views/ChargeBack/DeptPastRequisition.cshtml
@model IEnumerable<SSISTeam9.Models.Requisition>

@{
    ViewBag.Title = "DeptRequisition";
    string sessionId = (string)ViewData["sessionId"];
    string deptName = (string)ViewData["deptName"];

}

<link href="~/Content/sticky-footer-navbar.css" rel="stylesheet">
@{
    if (Model.ToArray().Length == 0)
    {
        <h2>@deptName doesn't have any requisition yet!</h2>
    }
    else
    {
        <h2>@deptName Completed Requisitions</h2>
        <br />
        <table class="table table-bordered">
            <tr>
                <th>
                    Requisition Code
                </th>
                <th>
                    Date Of Request
                </th>
            </tr>

            @foreach (var req in Model)
            {
            <tr>
                <td>
                    @Html.ActionLink(req.ReqCode.ToString(), "GetRequisitionDetails", "Requisition", new { reqId = req.ReqId, sessionId = sessionId },null)
                </td>
                <td>
                    @Html.DisplayFor(modelreq => req.DateOfRequest)
                </td>
            </tr>
            }

        </table>
    }
}

<style>
    td {
        padding: 2px;
        width: 200px;
    }

    tr {
        height: 40px;
        padding: 2px;
        text-align: center;
    }

    th {
        text-align: center;
    }
</style>

SSISTeam9/Views/ChargeBack/Select.cshtml
@model SSISTeam9.Models.ChargeBack

@using SSISTeam9.Models;

@{
    Layout = "~/Views/Shared/_Store.cshtml";
    ViewBag.Title = "Charge Back";

    List<ChargeBack> chargeBacks = (List<ChargeBack>)ViewData["chargeBacks"];
    List<string> months = (List<string>)ViewData["months"];
    List<int> years = (List<int>)ViewData["years"];
    List<string> depts = (List<string>)ViewData["depts"];
    int? mode = (int?)TempData["mode"];
    ChargeBack chargeback = (ChargeBack)ViewData["chargeback"];
    string sessionId = (string)ViewData["sessionId"];
}

<h2 style="text-align:center">ChargeBack Details</h2>

<div>
    @using (Html.BeginForm("Generate", "ChargeBack", new { mode = 1, sessionId = sessionId }, FormMethod.Post))
    {
        <div style="text-align:center">
            <label style="text-align:center;margin-top:10px;padding-right:8em">By Month: </label>
            <select name="monthOfOrder" id="monthOfOrder" style="width: 180px">
                @for (int i = 0; i < 12; i++)
                {
                    <option value="@(i+1)">@months[i]</option>
                }
            </select>
            <label style="padding-right:15.8em"></label>
            <input style="margin-left:10px;margin-top:10px;text-align:center" class="rounded" type="submit" value="Generate">
        </div>

    }
    @using (Html.BeginForm("Generate", "ChargeBack", new { mode = 2, sessionId = sessionId }, FormMethod.Post))
    {
        <div style="text-align:center">
            <label style="text-align:center;margin-top:10px;padding-right:5.7em">By Department: </label>
            <select name="yearOfOrder" id="yearOfOrder" style="width: 180px">
                @foreach (int year in years)
                {
                    <option>@year</option>
                }
            </select>
            <label style="padding-right:2em"></label>
            <select name="deptName" id="deptName" style="width: 180px">
                @foreach (string dept in depts)
                {
                    <option>@dept</option>
                }
            </select>
            <label style="padding-right:2em"></label>
            <input style="margin-left:10px;margin-top:10px;text-align:center" class="rounded" type="submit" value="Generate">
        </div>

    }

</div>
@if (chargeBacks == null || chargeBacks.Count == 0)
{
    <br /><br />
    <p style="font-size:14px; text-align:center">No ChargeBack to display</p>

}
else
{
    if (mode == 1)
    {
        <p style="text-align:center">Charge Back Details for All Departments in @months[chargeback.MonthOfOrder - 1]</p>
        <table class="table table-bordered" style="text-align:center">
            <tr align="center">
                <th>Department Name</th>
                <th>ChargeBack</th>
            </tr>
            @foreach (var c in chargeBacks)
            {
                <tr align="center">
                    <td><a href="/Disbursement/ViewDeptCompletedDisburse?deptId=@c.DeptId&sessionid=@sessionId">@c.DeptName </a></td>
                    <td>$@c.Amount</td>
                </tr>
            }
        </table>

    }
    else
    {
        <p style="text-align:center">Charge Back Details for <a href="/Disbursement/ViewDeptCompletedDisburse?deptId=@chargeback.DeptId&sessionid=@sessionId">@chargeback.DeptName </a>in @chargeback.YearOfOrder</p>
        <table class="table table-bordered" style="text-align:center">
            <tr align="center">
                <th>Month</th>
                <th>ChargeBack</th>
            </tr>
            @foreach (var c in chargeBacks)
            {
                <tr align="center">
                    <td>@months[c.MonthOfOrder - 1]</td>
                    <td>$@c.Amount</td>
                </tr>
            }
        </table>
    }
}