SSISTeam9/Models/AdjVoucher.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;

namespace SSISTeam9.Models
{
    public class AdjVoucher
    {
        public long AdjId { get; set; }
        public DateTime Date { get; set; }
        public long AuthorisedBy { get; set; }
        public int AdjQty { get; set; }
        
        [Required(AllowEmptyStrings = false, ErrorMessage ="Required")]
        public string Reason { get; set; }
        public long ItemId { get; set; }
        public string ItemCode { get; set; }
        public string Description { get; set; }

        public double UnitPrice { get; set; }

        public double TotalPrice { get; set; }

        //0-pending 1-authorised 2-pending authorisation by Supervisor 3-pending authorisation by Manager
        public int status { get; set; }

        public Inventory Item { get; set; }
    }
}

SSISTeam9/Controllers/AdjVoucherController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using SSISTeam9.Models;
using SSISTeam9.Services;
using System.Threading.Tasks;
using SSISTeam9.Filters;

namespace SSISTeam9.Controllers
{
    [StoreAuthorisationFilter]
    public class AdjVoucherController : Controller
    {
        

        public ActionResult Index(string sessionId)
        {
            Employee user = EmployeeService.GetUserBySessionId(sessionId);
            if (user.EmpRole == "STORE_SUPERVISOR" || user.EmpRole == "STORE_MANAGER")
            {
                return RedirectToAction("PendingApprove", new { sessionId});
            }
            else
            {
                return RedirectToAction("PutReason", new { sessionId });
            }

        }

        /*
        public ActionResult Generate(List<Inventory> inventories, string sessionId)
        {
            long adjId = (long)AdjVoucherService.GetLastId() + 1;
            int flag = 0;
            foreach (Inventory inventory in inventories)
            {
                int qty = inventory.ActualStock - inventory.StockLevel;
                if (qty != 0)
                {
                    flag = 1;
                    AdjVoucherService.CreateAdjVoucher(adjId, inventory.ItemId, qty);
                    StockService.UpdateInventoryStockById(inventory.ItemId, inventory.ActualStock);
                }
            }
            if(flag == 0)
            {
                TempData["errorMsg"] = "<script>alert('There are no discrepancies in stock.');</script>";
                ViewData["userName"] = EmployeeService.GetUserBySessionId(sessionId).EmpName;
                ViewData["sessionId"] = sessionId;
                return View("~/Views/StoreLandingPage/Home.cshtml");
            }


            return RedirectToAction("PutReason", new { sessionId});
        }*/


        public ActionResult Generate(Inventory item, FormCollection formCollection, string sessionId)
        {
            List<int> itemsQuantities = new List<int>();
            List<long> itemIds = new List<long>();
            long adjId = (long)AdjVoucherService.GetLastId() + 1;
            int flag = 0;

            string counter = formCollection["counter"];

            for (int i = 0; i < int.Parse(counter); i++)
            {
                int actualStock = int.Parse(formCollection["actualStock_" + i]);
                int lastStock = int.Parse(formCollection["lastStock_" + i]);
                int qty = actualStock - lastStock;
                if (qty != 0)
                {
                    flag = 1;
                    long itemId = long.Parse(formCollection["itemId_" + i]);
                    AdjVoucherService.CreateAdjVoucher(adjId, itemId, qty);

                    //Update Inventory with new stock level
                    StockService.UpdateInventoryStockById(itemId, actualStock);
                    //The function below is for update stock card
                    //By the time authorise adjustment voucher, update StockCard table with itemId and date, souceType = 1
                    StockCardService.CreateStockCardFromAdj(adjId, itemId, qty);
                }
            }
            if (flag == 0)
            {
                TempData["errorMsg"] = "<script>alert('There are no discrepancies in stock.');</script>";
                ViewData["userName"] = EmployeeService.GetUserBySessionId(sessionId).EmpName;
                ViewData["sessionId"] = sessionId;
                return View("~/Views/StoreLandingPage/Home.cshtml");
            }
            return RedirectToAction("PutReason", new { sessionId });
        }





        public ActionResult PutReason(string sessionId)
        {
            List<AdjVoucher> adjVouchers = new List<AdjVoucher>();

            //status = 0 means need to be submit for reason.
            adjVouchers = AdjVoucherService.GetAdjByStatus(0);
            if(adjVouchers.Count == 0)
            {
                return RedirectToAction("AllAdjVouchers", new { sessionId });
            }
            else
            {
                foreach (AdjVoucher adj in adjVouchers)
                {
                    adj.Reason = null;
                    adj.Item = CatalogueService.GetCatalogueById(adj.ItemId);
                    adj.Item.ItemSuppliersDetails = PurchaseOrderService.GetItemSuppliersDetails(adj.ItemId);
                }
                ViewData["adjVouchers"] = adjVouchers;
                ViewData["sessionId"] = sessionId;
                return View();
            }
            
        }

        public ActionResult UpdateReason(List<AdjVoucher> adjVouchers, string sessionId)
        {
            Employee user = EmployeeService.GetUserBySessionId(sessionId);
            double totalAmount = 0;

            //To check if user entered reason and if not, to return back to form to show validation message
            foreach (AdjVoucher adj in adjVouchers)
            {
                if (string.IsNullOrWhiteSpace(adj.Reason))
                {
                    ViewData["adjVouchers"] = adjVouchers;
                    ViewData["sessionId"] = sessionId;
                    return View("PutReason");
                }
            }

            foreach (AdjVoucher adj in adjVouchers)
            {
                PriceList priceList = PriceListService.GetPriceListByItemId(adj.ItemId);
                double price = 0;
                if (priceList != null)
                {
                    price = priceList.Supplier1UnitPrice;
                }

                double amount = price * adj.AdjQty;
                totalAmount = totalAmount + amount;
                AdjVoucherService.UpdateReason(adj);
            }

            if (totalAmount > -250)
            {
                //status = 2, Pending authorisation by Supervisor
                long adjId = 0;
                foreach (AdjVoucher adj in adjVouchers)
                {
                    if (adj.AdjId != adjId)
                    {
                        adjId = adj.AdjId;
                        AdjVoucherService.UpdateStatus(adjId, 2);
                    }
                }
                //Inform Store supervisor
                List<Employee> supervisors = new List<Employee>();
                EmailNotification notice = new EmailNotification();
                supervisors = EmployeeService.GetEmployeeByRole("STORE_SUPERVISOR");
                foreach(Employee s in supervisors)
                {                    
                    notice.ReceiverMailAddress = EmployeeService.GetUserEmail(s.EmpId);
                    EmailService emailService = new EmailService();
                    Task.Run(() => emailService.SendMail(notice, EmailTrigger.ON_PENDING_ADJVOUCHER));
                }
                TempData["errorMsg"] = "<script>alert('Total discrepancy amount is less than $250, pending for Store Supervisor to authorise.');</script>";
            }
            else
            {
                //status = 3, Pending authorisation by Manager
                long adjId = 0;
                foreach (AdjVoucher adj in adjVouchers)
                {
                    if (adj.AdjId != adjId)
                    {
                        adjId = adj.AdjId;
                        AdjVoucherService.UpdateStatus(adjId, 3);
                    }
                }

                //Inform manager
                List<Employee> managers = new List<Employee>();
                EmailNotification notice = new EmailNotification();
                managers = EmployeeService.GetEmployeeByRole("STORE_MANAGER");
                foreach (Employee m in managers)
                {
                    notice.ReceiverMailAddress = EmployeeService.GetUserEmail(m.EmpId);
                    EmailService emailService = new EmailService();
                    Task.Run(() => emailService.SendMail(notice, EmailTrigger.ON_PENDING_ADJVOUCHER));
                }
                TempData["errorMsg"] = "<script>alert('Total discrepancy amount is more than $250, pending for Store Manager to authorise.');</script>";

            }
            ViewData["userName"] = user.EmpName;
            ViewData["sessionId"] = sessionId;
            return View("~/Views/StoreLandingPage/Home.cshtml");
        }


        //public ActionResult AuthoriseByS(List<AdjVoucher> adjVouchers, string sessionId)
        //{
        //    Employee user = EmployeeService.GetUserBySessionId(sessionId);
        //    double totalAmount = 0;
        //    foreach (AdjVoucher adj in adjVouchers)
        //    {
        //        PriceList priceList = PriceListService.GetPriceListByItemId(adj.ItemId);
        //        double price = 0;
        //        if (priceList != null)
        //        {
        //            price = priceList.Supplier1UnitPrice;
        //        }

        //        double amount = price * adj.AdjQty;
        //        totalAmount = totalAmount + amount;
        //        AdjVoucherService.UpdateReason(adj);
        //    }

        //    if (totalAmount > -250)
        //    {
        //        //status = 1, auto approved by supervisor
        //        AdjVoucherService.UpdateStatus(adjVouchers[0].AdjId, 1);
        //        AdjVoucherService.AuthoriseBy(adjVouchers[0].AdjId, user.EmpId);
        //        TempData["errorMsg"] = "<script>alert('Total discrepancy is less than $250, authorised already.');</script>";
        //    }
        //    else
        //    {
        //        //status = 2, pending approve for manager
        //        AdjVoucherService.UpdateStatus(adjVouchers[0].AdjId, 2);
        //        TempData["errorMsg"] = "<script>alert('Total discrepancy is more than $250, pending for Store Manager to authorise.');</script>";

        //    }
        //    ViewData["userName"] = user.EmpName;
        //    ViewData["sessionId"] = sessionId;
        //    return View("~/Views/StoreLandingPage/Home.cshtml");

SSISTeam9/Views/AdjVoucher/AdjDetails.cshtml
@using SSISTeam9.Models;
@{
    Layout = "~/Views/Shared/_Store.cshtml";
    ViewBag.Title = "Inventory Adjustment Voucher";
    List<AdjVoucher> adjVouchers = (List<AdjVoucher>)ViewData["adjVouchers"];
    string sessionId = (string)ViewData["sessionId"];
    string adjIdstring = (string)ViewData["adjIdstring"];
    string authorisedBy = (string)ViewData["authorisedBy"];
}

@if (adjVouchers.Count == 0)
{
    <br /><br />
    <p style="font-size:14px">No adjustment voucher to display</p>
}
else
{
    <h2 style="text-align:center">Adjustment Voucher</h2>
    <p>Possible Causes:</p>
    <p style="padding-left:3em">1. items broken or expired</p>
    <p style="padding-left:3em">2. adhoc (i.e. detected when trying to issue the item(s))</p>
    <p style="padding-left:3em">3. when issue/receipt of item is not recorded (i.e. oversight)</p>

    <h5>Authorising Adjustments:</h5>
    <p>Minor: - anything under $250 per item adjustment can be authorised by Supervisor</p>
    <p style="padding-left:3em">- a copy of adjustment amounts is put on an adjustment voucher and is signed by the supervisor.</p><br />
    <p>Major: - by Manager</p>
    <p style="padding-left:3em">- use adjustment voucher</p>
    <p style="padding-left:3em">- a copy of adjustment amounts is put on an adjustment voucher and is signed by the supervisor.</p>
    <h4 style="text-align:center">Voucher#: @adjIdstring</h4>
    <p>Date: @adjVouchers[0].Date.ToShortDateString()</p>
    <section>
        <table class="table table-bordered" style="text-align:center" align="center">
            <tr align="center">
                <th>Item Code</th>
                <th>Description</th>
                <th>Quantity adjusted</th>
                <th>Reason</th>
                <th>Unit Price</th>
                <th>Total Price</th>
            </tr>

            @foreach (AdjVoucher adj in adjVouchers)
            {

                <tr>
                    <td>@adj.ItemCode</td>
                    <td>@adj.Description</td>
                    <td>@adj.AdjQty</td>
                    <td>@adj.Reason</td>
                    <td>$@adj.UnitPrice</td>
                    <td>$@adj.TotalPrice</td>
                </tr>
            }
        </table>
        <p style="float:inherit;text-align :right">Authorised by: @authorisedBy</p>
    </section>
}

SSISTeam9/Views/AdjVoucher/AllAdjVouchers.cshtml
@using SSISTeam9.Models;
@{
    Layout = "~/Views/Shared/_Store.cshtml";
    ViewBag.Title = "Adjustment Voucher Lists";
    List<string> dates = (List<string>)ViewData["dates"];
    List<string> authorisedBys = (List<string>)ViewData["authorisedBys"];
    List<string> statuses = (List<string>)ViewData["statuses"];
    List<string> adjIds = (List<string>)ViewData["adjIds"];
    string sessionId = (string)ViewData["sessionId"];
}

@if (dates.Count == 0)
{
    <br /><br />
    <p style="font-size:14px">No adjustment voucher to display.</p>
}
else
{
    <table align="center" class="table table-bordered">
        
        <tr align="center">
            <th>AdjVoucher Id</th>
            <th>Authorised By</th>
            <th>Date</th>
            <th>Status</th>
        </tr>
        @for(int i = 0; i < adjIds.Count; i++)
        {
            <tr align="center">
                <td><a href="/AdjVoucher/AdjDetails?adjId=@(i + 1)&sessionId=@sessionId">@adjIds[i] </a></td>
                <td>@authorisedBys[i]</td>
                <td>@dates[i]</td>
                <td>@statuses[i]</td>
            </tr>
        }
    </table>
}

SSISTeam9/Views/AdjVoucher/AllAprovedAdj.cshtml
@{
    ViewBag.Title = "AllAprovedAdj";
}

<h2>AllAprovedAdj</h2>

SSISTeam9/Views/AdjVoucher/Generate.cshtml
@model List<SSISTeam9.Models.AdjVoucher>

@using (Html.BeginForm())
{
    <table class="table">

        <thead>
            <tr align="center">
                <th>Item Code</th>
                <th>Description</th>
                <th>Quantity Adjusted</th>
                <th>Reason</th>
                <th>Unit Price</th>
                <th>Total Price</th>
            </tr>

        </thead>

        <tbody>
        <tr><td>@ViewBag.Msg
        </td></tr>
        </tbody>

    </table>
}

SSISTeam9/Views/AdjVoucher/Index.cshtml
@model List<SSISTeam9.Models.AdjVoucher>

@using (Html.BeginForm("Generate", "AdjVoucher", Model, FormMethod.Post))
{
    <table class="table table-bordered">

        <thead>
        <tr align="center">
            <th>Item Code</th>
            <th>Description</th>
            <th>Quantity Adjusted</th>
            <th>Reason</th>
            <th>Unit Price</th>
            <th>Total Price</th>
        </tr>

        </thead>

        <tbody>

        @if (Model != null)
        {
            for (var i = 0; i < Model.Count; i++)
            {
                <tr>
                    <td>@Html.DisplayFor(x => Model[i].Item.ItemCode)</td>
                    <td>@Html.DisplayFor(x => Model[i].Item.Description)</td>

                    <td>@Html.DisplayFor(x => Model[i].AdjQty)</td>
                    <td>@Html.TextBoxFor(x => Model[i].Reason)</td>
                    <td>@Model[i].Item.ItemSuppliersDetails.Supplier1UnitPrice / @Model[i].Item.UnitOfMeasure</td>
                    <td>@Html.DisplayFor(x => Model[i].TotalPrice)</td>
                    @Html.HiddenFor(x => Model[i].Item.ItemCode)
                    @Html.HiddenFor(x => Model[i].Item.ItemId)
                    @Html.HiddenFor(x => Model[i].AdjQty)
                    @Html.HiddenFor(x => Model[i].Item.Description)
                    @Html.HiddenFor(x => Model[i].TotalPrice)
                </tr>
            }
        }

        </tbody>


    </table>
    <input type="submit" value="Generate Adjustment Voucher"/>
}

SSISTeam9/Views/AdjVoucher/PendingApprove.cshtml
@using SSISTeam9.Models;
@{
    Layout = "~/Views/Shared/_Store.cshtml";
    ViewBag.Title = "Inventory Adjustment Voucher";
    List<AdjVoucher> adjVouchers = (List<AdjVoucher>)ViewData["adjVouchers"];
    string sessionId = (string)ViewData["sessionId"];
    string authoriseBy = (string)ViewData["authoriseBy"];
    double total = 0;
    Dictionary<long, List<AdjVoucher>> byVouchers = (Dictionary<long, List<AdjVoucher>>)ViewData["byVouchers"];
}

<h2  style="text-align:center">Adjustment Vouchers to be Authorised by @authoriseBy</h2>

@if (adjVouchers.Count == 0)
{
    <br /><br />
    <p style="font-size:14px">There are no outstanding adjustment vouchers to be authorised.</p>
}
else
{
    foreach (KeyValuePair<long, List<AdjVoucher>> adj in byVouchers)
    {
        <h5>Voucher ID: @adj.Key</h5>
        <table class="table table-bordered" align="center">
            <tr align="center">
                <th>Item Code</th>
                <th>Description</th>
                <th>Quantity Adjusted</th>
                <th>Reason</th>
                <th>Unit Price</th>
                <th>Total Price</th>
            </tr>
            @for (int i = 0; i < (adj.Value.Count); i++)
            {
                <tr style="text-align:center">
                    <td>@adj.Value[i].ItemCode</td>
                    <td>@adj.Value[i].Item.Description</td>
                    <td>@adj.Value[i].AdjQty</td>
                    <td>@adj.Value[i].Reason</td>
                    <td>@(adj.Value[i].Item.ItemSuppliersDetails.Supplier1UnitPrice.ToString("C2") + "/" + adj.Value[i].Item.UnitOfMeasure)</td>
                    <td>@((adj.Value[i].Item.ItemSuppliersDetails.Supplier1UnitPrice * adj.Value[i].AdjQty).ToString("C2"))</td>
                </tr>
                total = total + adj.Value[i].Item.ItemSuppliersDetails.Supplier1UnitPrice * adj.Value[i].AdjQty;
            }
            <tr>
                <td colspan="5" style="text-align:right;font-weight:bold">Total:</td>
                <td style="text-align:center">@total.ToString("C2")</td>
            </tr>
        </table>
        total = 0;
    }

    @*<table class="table table-bordered" align="center">
            <tr align="center">
                <th>Item Code</th>
                <th>Description</th>
                <th>Quantity Adjusted</th>
                <th>Reason</th>
                <th>Unit Price</th>
                <th>Total Price</th>
            </tr>
            @for (int i = 0; i < adjVouchers.Count; i++)
            {
                <tr style="text-align:center">
                    <td>@adjVouchers[i].ItemCode</td>
                    <td>@adjVouchers[i].Item.Description</td>
                    <td>@adjVouchers[i].AdjQty</td>
                    <td>@adjVouchers[i].Reason</td>
                    <td>@(adjVouchers[i].Item.ItemSuppliersDetails.Supplier1UnitPrice.ToString("C2") + "/" + adjVouchers[i].Item.UnitOfMeasure)</td>
                    <td>@(Math.Abs(adjVouchers[i].Item.ItemSuppliersDetails.Supplier1UnitPrice * adjVouchers[i].AdjQty).ToString("C2"))</td>
                </tr>
                total = total + Math.Abs(adjVouchers[i].Item.ItemSuppliersDetails.Supplier1UnitPrice * adjVouchers[i].AdjQty);
            }
            <tr>
                <td colspan="5" style="text-align:right;font-weight:bold">Total:</td>
                <td style="text-align:center">@total.ToString("C2")</td>
            </tr>
        </table>*@
    <input class="rounded" type="button" value="Authorise" style="margin-left:10px;float:right" onclick="location.href='@Url.Action("Authorise","AdjVoucher", new {sessionid = sessionId})'">
}

<footer>
    <div id="notes" style="margin-top:200px;font-size:12px">
        <p><u>Notes</u></p>
        <p>1. Inventory Adjustments. Possible Causes: </p>
        <ul>
            <li>items broken or expired</li>
            <li>adhoc i.e. detected when trying to issue the item(s)</li>
            <li>when issue/receipt of item is not recorded i.e. oversight</li>
        </ul>
        <p>2. Authorising Adjustments: </p>
        <ul>
            <li>Minor: anything under $250 per adjustment can be authorised by Supervisor</li>
            <li>Major: anything above $250 per adjustment has to be authorised by Manager</li>
        </ul>
    </div>
</footer>

SSISTeam9/Views/AdjVoucher/PutReason.cshtml
@model List<SSISTeam9.Models.AdjVoucher>

@using SSISTeam9.Models;
@{
    Layout = "~/Views/Shared/_Store.cshtml";
    ViewBag.Title = "Inventory Adjustment Voucher";
    List<AdjVoucher> adjVouchers = (List<AdjVoucher>)ViewData["adjVouchers"];
    string sessionId = (string)ViewData["sessionId"];
    double total = 0;
}

<h3>Generate Adjustment Voucher</h3>

@if (adjVouchers.Count == 0)
{
    <br /><br />
    <p style="font-size:14px">No adjustment voucher to display</p>
}
else
{
    using (Html.BeginForm("UpdateReason", "AdjVoucher", new { sessionId = sessionId }, FormMethod.Post))
    {
        <table class="table table-bordered" align="center">
            <tr style="text-align:center">
                <th>Item Code</th>
                <th>Description</th>
                <th>Quantity Adjusted</th>
                <th>Reason</th>
                <th>Unit Price</th>
                <th>Total Price</th>
            </tr>
            @for (int i = 0; i < adjVouchers.Count; i++)
            {
            <tr style="text-align:center">
                <td>@adjVouchers[i].ItemCode</td>
                <td>@adjVouchers[i].Item.Description</td>
                <td>@adjVouchers[i].AdjQty</td>
                <td>
                    @Html.TextBoxFor(x => x[i].Reason, new { id = "reason" })
                    @Html.ValidationMessageFor(x => x[i].Reason, "", new { style = "color:red" })
                </td>
                <td>@(adjVouchers[i].Item.ItemSuppliersDetails.Supplier1UnitPrice.ToString("C2") + "/" + adjVouchers[i].Item.UnitOfMeasure)</td>
                <td>@((adjVouchers[i].Item.ItemSuppliersDetails.Supplier1UnitPrice * adjVouchers[i].AdjQty).ToString("C2"))</td>
                <td style="display:none">
                    @Html.TextBoxFor(x => x[i].ItemId, new { id = "itemId", @Value = adjVouchers[i].ItemId })
                    @Html.TextBoxFor(x => x[i].AdjId, new { id = "adjId", @Value = adjVouchers[i].AdjId })
                    @Html.TextBoxFor(x => x[i].AdjQty, new { id = "adjQty", @Value = adjVouchers[i].AdjQty })
                </td>
            </tr>
                total = total + adjVouchers[i].Item.ItemSuppliersDetails.Supplier1UnitPrice * adjVouchers[i].AdjQty;
            }
            <tr>
                <td colspan="5" style="text-align:right;font-weight:bold">Total:</td>
                <td style="text-align:center">@total.ToString("C2")</td>
            </tr>
        </table>
        <input class="rounded" style="float:right;margin-bottom:30px" type="submit" value="Generate Adjustment Voucher">
    }
}

<footer>
    <div id="notes" style="margin-top:200px;font-size:12px">
        <p><u>Notes</u></p>
        <p>1. Inventory Adjustments. Possible Causes: </p>
        <ul>
            <li>items broken or expired</li>
            <li>adhoc i.e. detected when trying to issue the item(s)</li>
            <li>when issue/receipt of item is not recorded i.e. oversight</li>
        </ul>
        <p>2. Authorising Adjustments: </p>
        <ul>
            <li>Minor: anything under $250 per adjustment can be authorised by Supervisor</li>
            <li>Major: anything above $250 per adjustment has to be authorised by Manager</li>
        </ul>
    </div>
</footer>